import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const moduleRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(moduleRoot, "../..");

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

test("public API contract pins strict source type checking", () => {
  const packageJson = readJson(resolve(moduleRoot, "package.json"));
  const tsconfig = readJson(resolve(moduleRoot, "tsconfig.json"));

  assert.equal(packageJson.name, "@superi/api-client-contract");
  assert.equal(packageJson.private, true);
  assert.equal(packageJson.scripts.typecheck, "tsc --noEmit");
  assert.equal(packageJson.devDependencies.typescript, "5.9.3");
  assert.equal(packageJson.devDependencies.vite, undefined);
  assert.equal(tsconfig.compilerOptions.strict, true);
  assert.equal(tsconfig.compilerOptions.noEmit, true);
  assert.deepEqual(tsconfig.include, ["src"]);
});

test("contract consumes the committed generated public API bindings", () => {
  const consumer = readFileSync(resolve(moduleRoot, "src/api-contract.ts"), "utf8");
  const bindings = readFileSync(
    resolve(repositoryRoot, "open/bindings/typescript/superi-api.ts"),
    "utf8",
  );

  assert.match(consumer, /open\/bindings\/typescript\/superi-api/);
  assert.match(consumer, /superi\.project\.command\.execute/);
  assert.match(consumer, /superi\.project\.command_log\.get/);
  assert.match(consumer, /superi\.api\.version\.negotiate/);
  assert.match(consumer, /versionNegotiationRequest/);
  assert.match(consumer, /superi\.project\.state\.changed/);
  assert.match(consumer, /superi\.editor\.state/);
  assert.match(consumer, /superi\.extensions\.get/);
  assert.match(consumer, /superi\.extensions\.changed/);
  assert.match(bindings, /^\/\/ Generated by superi-api-bindings\./);
  assert.match(bindings, /export interface SuperiMethodMap/);
  assert.match(bindings, /export interface SuperiEventMap/);
  assert.match(bindings, /export interface SuperiResourceMap/);
  assert.match(bindings, /export class SuperiClient/);
  assert.match(bindings, /export type NegotiateApiVersion/);
  assert.match(bindings, /export type ExtensionRegistrySnapshot/);
  assert.match(bindings, /export type GetProjectCommandLog/);
  assert.match(bindings, /export type ProjectCommandLogRecord/);
});

test("workflow runs both transport-neutral TypeScript contracts", () => {
  const workflow = readFileSync(
    resolve(repositoryRoot, ".github/workflows/typescript-contracts.yml"),
    "utf8",
  );

  assert.match(workflow, /permissions:\n  contents: read/);
  assert.match(workflow, /ci\/api-client-contract/);
  assert.match(workflow, /open\/bindings\/typescript\/editorial-contracts/);
  assert.match(workflow, /run: npm ci/);
  assert.match(workflow, /run: npm run typecheck/);
  assert.match(workflow, /run: npm test/);
  assert.doesNotMatch(workflow, /vite|frontend|tauri|webview/i);
});
